//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_SebastianOrtiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecStamp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExecStamp()
        {
            this.ExecStamp_Details = new HashSet<ExecStamp_Details>();
        }
    
        public int IdExecStamp { get; set; }
        public string Identification { get; set; }
        public System.DateTime DateStamp { get; set; }
        public System.TimeSpan TimeStamp { get; set; }
        public int Type { get; set; }
        public string ElementList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecStamp_Details> ExecStamp_Details { get; set; }
    }
}
